name: "Pull Request Labeler"

on:
  pull_request_target:
    types: [opened, synchronize]

permissions: {}

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: srvaroa/labeler@fe4b1c73bb8abf2f14a44a6912a8b4fee835d631 # v1.12.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
